spring:
  datasource:
    url: jdbc:h2:mem:paymentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    root: INFO
    uno.y: DEBUG
    org.hibernate.SQL: DEBUG

payment:
  retry:
    max-attempts: 3
    delay-ms: 1000
  providers:
    provider-a:
      name: PROVIDER_A
      supported-method: CARD
    provider-b:
      name: PROVIDER_B
      supported-method: UPI