server:
  port: 8080
  servlet:
    context-path: /api/payment-service

spring:
  application:
    name: payment-service

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, info